---
title: "Tipos de filme de Anne Hathaway"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(cluster)
library(plotly)
library(ggdendro)

source(here::here("code/lib.R"))
theme_set(theme_report())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = TRUE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r}
## ANTES DE USAR
# Para criar data/movies.csv
anne_hathaway = import_data("anne_hathaway") #ou com o ator/atriz que você escolher
```


```{r read}
filmes = read_imported_data()
```

## Descrição

```{r}
filmes %>% 
    ggplot(aes(x = ano, y = bilheteria)) + 
    geom_point(size = 4, color = paleta[1]) 
```



```{r}
filmes %>% 
    ggplot(aes(x = bilheteria)) + 
    geom_histogram(fill = paleta[2], color = "black", bins = 5) + scale_x_log10() + geom_rug()
```

```{r}
filmes %>% 
    ggplot(aes(x = avaliacao)) + 
    geom_histogram(binwidth = 10, boundary = 0, fill = paleta[3], color = "black") + 
    geom_rug(size = .5) 
```

## Estrutura de grupos?

```{r}
p = filmes %>% 
    ggplot(aes(x = avaliacao, y = bilheteria, label = filme)) + 
    geom_jitter(width = .05, alpha = .3, size = 3) + 
    labs(x = 'Avaliação')

ggplotly(p)
```

## Agrupamento hierárquico

```{r}
agrupamento_h = filmes %>% 
    mutate(nome = paste0(filme, " (av=", avaliacao, ")")) %>% 
    as.data.frame() %>% 
    column_to_rownames("filme") %>% 
    select(avaliacao) %>%
    dist(method = "euclidean") %>% 
    hclust(method = "centroid")

agrupamento_h_2d = filmes %>% 
    mutate(bilheteria = log10(bilheteria)) %>%
    mutate_at(vars(avaliacao, bilheteria), 
              funs(scale)) %>% 
    as.data.frame() %>%
    column_to_rownames("filme") %>%
    select(avaliacao, bilheteria) %>%
    dist(method = "euclidean") %>% 
    hclust(method = "ward.D")


ggdendrogram(agrupamento_h_2d, rotate = T, size = 2, theme_dendro = F) + 
    labs(y = "Dissimilaridade", x = "", title = "Dendrograma")
```

```{r}
get_grupos <- function(agrupamento, num_grupos){
    agrupamento %>% 
        cutree(num_grupos) %>% 
        as.data.frame() %>% 
        mutate(label = rownames(.)) %>% 
        gather(key =  "k", value = "grupo", -label) %>% 
        mutate(grupo = as.character(grupo))
}

atribuicoes = get_grupos(agrupamento_h_2d, num_grupos = 1:6)

atribuicoes = atribuicoes %>% 
    left_join(filmes, by = c("label" = "filme"))

atribuicoes %>% 
    mutate(bilheteria = log10(bilheteria)) %>%
    ggplot(aes(x = bilheteria, y = avaliacao, colour = grupo)) + 
    geom_jitter(width = .02, height = 0, size = 1.6, alpha = .6) + 
    facet_wrap(~ paste(k, " grupos")) + 
    scale_color_brewer(palette = "Dark2")

```

```{r}
k_escolhido = 4

p <- atribuicoes %>% 
    filter(k == k_escolhido) %>% 
    ggplot(aes(x = bilheteria, y = avaliacao, colour = grupo, label = label)) + 
    geom_jitter(width = .02, height = 0, size = 3, alpha = .6) + 
    facet_wrap(~ paste(k, " tipos de filmes de Anne Hathaway")) + 
    scale_color_brewer(palette = "Dark2") + 
    labs(x = "Bilheteria", y = "Avaliação") + coord_flip() + 
    theme(legend.position = "none")

ggplotly(p)
```

  Anne Hathaway possui filmes que estão em 4 grupos: 
  * Sucesso de bilheteria e com baixa avaliação dos usuários;
  * Sucesso de bilheteria e com média avaliação dos usuários;
  * Sucesso de bilheteria e com alta avaliação dos usuários;
  * Fracassos de bilheteria e com alta avaliação dos usuários;
